// <auto-generated />
using System;
using Asistant_Infra_Db_Sql.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asistant_Infra_Db_Sql.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Asistant_Domain_Core.CommentAgg.Entity.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<int>("HomeServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpertId");

                    b.HasIndex("HomeServiceId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Asistant_Domain_Core.HomeServiceAgg.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageId = 1,
                            Name = "نظافت منزل"
                        },
                        new
                        {
                            Id = 2,
                            ImageId = 2,
                            Name = "تعمیرات لوازم خانگی"
                        },
                        new
                        {
                            Id = 3,
                            ImageId = 3,
                            Name = "خدمات برقکاری"
                        },
                        new
                        {
                            Id = 4,
                            ImageId = 4,
                            Name = "خدمات لوله‌کشی"
                        },
                        new
                        {
                            Id = 5,
                            ImageId = 5,
                            Name = "خدمات نقاشی و دکوراسیون"
                        },
                        new
                        {
                            Id = 6,
                            ImageId = 6,
                            Name = "خدمات باغبانی"
                        },
                        new
                        {
                            Id = 7,
                            ImageId = 7,
                            Name = "خدمات کامپیوتر و شبکه"
                        },
                        new
                        {
                            Id = 8,
                            ImageId = 8,
                            Name = "خدمات خودرو"
                        },
                        new
                        {
                            Id = 9,
                            ImageId = 9,
                            Name = "خدمات آموزشی"
                        },
                        new
                        {
                            Id = 10,
                            ImageId = 10,
                            Name = "خدمات پزشکی و پرستاری"
                        });
                });

            modelBuilder.Entity("Asistant_Domain_Core.HomeServiceAgg.Entities.HomeService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("HomeServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 300000m,
                            CategoryId = 1,
                            Description = "تمیزکاری کامل کابینت‌ها، کف و دیوارها",
                            ImageId = 11,
                            Name = "نظافت آشپزخانه"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 200000m,
                            CategoryId = 1,
                            Description = "گردگیری و جاروکشی اتاق‌ها",
                            ImageId = 12,
                            Name = "نظافت اتاق‌ها"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 250000m,
                            CategoryId = 1,
                            Description = "شستشو و ضدعفونی سرویس‌ها",
                            ImageId = 13,
                            Name = "نظافت سرویس بهداشتی"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 500000m,
                            CategoryId = 2,
                            Description = "عیب‌یابی و تعمیر انواع ماشین لباسشویی",
                            ImageId = 14,
                            Name = "تعمیر ماشین لباسشویی"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 600000m,
                            CategoryId = 2,
                            Description = "سرویس و تعمیر یخچال و فریزر",
                            ImageId = 15,
                            Name = "تعمیر یخچال"
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 150000m,
                            CategoryId = 3,
                            Description = "نصب و تعویض کلید و پریز برق",
                            ImageId = 16,
                            Name = "نصب کلید و پریز"
                        },
                        new
                        {
                            Id = 7,
                            BasePrice = 800000m,
                            CategoryId = 3,
                            Description = "اجرای سیم‌کشی برق داخلی",
                            ImageId = 17,
                            Name = "سیم‌کشی ساختمان"
                        },
                        new
                        {
                            Id = 8,
                            BasePrice = 250000m,
                            CategoryId = 4,
                            Description = "باز کردن لوله‌های فاضلاب و آب",
                            ImageId = 18,
                            Name = "رفع گرفتگی لوله"
                        },
                        new
                        {
                            Id = 9,
                            BasePrice = 200000m,
                            CategoryId = 4,
                            Description = "نصب و تعویض شیرآلات آشپزخانه و حمام",
                            ImageId = 19,
                            Name = "نصب شیرآلات"
                        },
                        new
                        {
                            Id = 10,
                            BasePrice = 400000m,
                            CategoryId = 5,
                            Description = "رنگ‌آمیزی دیوارهای داخلی",
                            ImageId = 20,
                            Name = "نقاشی دیوار"
                        },
                        new
                        {
                            Id = 11,
                            BasePrice = 700000m,
                            CategoryId = 5,
                            Description = "نصب انواع کاغذ دیواری",
                            ImageId = 21,
                            Name = "کاغذ دیواری"
                        },
                        new
                        {
                            Id = 12,
                            BasePrice = 350000m,
                            CategoryId = 6,
                            Description = "هرس و مرتب‌سازی درختان باغ و حیاط",
                            ImageId = 22,
                            Name = "هرس درختان"
                        },
                        new
                        {
                            Id = 13,
                            BasePrice = 300000m,
                            CategoryId = 6,
                            Description = "کاشت و نگهداری گل‌ها و گیاهان",
                            ImageId = 23,
                            Name = "کاشت گل و گیاه"
                        },
                        new
                        {
                            Id = 14,
                            BasePrice = 200000m,
                            CategoryId = 7,
                            Description = "نصب و راه‌اندازی سیستم عامل ویندوز",
                            ImageId = 24,
                            Name = "نصب ویندوز"
                        },
                        new
                        {
                            Id = 15,
                            BasePrice = 400000m,
                            CategoryId = 7,
                            Description = "نصب مودم و تنظیم شبکه داخلی",
                            ImageId = 25,
                            Name = "راه‌اندازی شبکه خانگی"
                        },
                        new
                        {
                            Id = 16,
                            BasePrice = 150000m,
                            CategoryId = 8,
                            Description = "تعویض روغن موتور خودرو",
                            ImageId = 26,
                            Name = "تعویض روغن"
                        },
                        new
                        {
                            Id = 17,
                            BasePrice = 250000m,
                            CategoryId = 8,
                            Description = "نصب و تعمیر باتری خودرو",
                            ImageId = 27,
                            Name = "باتری‌سازی"
                        },
                        new
                        {
                            Id = 18,
                            BasePrice = 500000m,
                            CategoryId = 9,
                            Description = "کلاس خصوصی زبان انگلیسی",
                            ImageId = 28,
                            Name = "آموزش زبان انگلیسی"
                        },
                        new
                        {
                            Id = 19,
                            BasePrice = 400000m,
                            CategoryId = 9,
                            Description = "کلاس تقویتی ریاضی",
                            ImageId = 29,
                            Name = "آموزش ریاضی"
                        },
                        new
                        {
                            Id = 20,
                            BasePrice = 700000m,
                            CategoryId = 10,
                            Description = "مراقبت از بیمار در منزل",
                            ImageId = 30,
                            Name = "پرستاری در منزل"
                        },
                        new
                        {
                            Id = 21,
                            BasePrice = 800000m,
                            CategoryId = 10,
                            Description = "ویزیت پزشک در منزل",
                            ImageId = 31,
                            Name = "ویزیت پزشک عمومی"
                        });
                });

            modelBuilder.Entity("Asistant_Domain_Core.ImageAgg.Entity.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("ExpertId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeServiceId")
                        .HasColumnType("int");

                    b.Property<int>("ImageCategory")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int");

                    b.Property<int?>("SuggestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .IsUnique()
                        .HasFilter("[CategoryId] IS NOT NULL");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasFilter("[CustomerId] IS NOT NULL");

                    b.HasIndex("ExpertId")
                        .IsUnique()
                        .HasFilter("[ExpertId] IS NOT NULL");

                    b.HasIndex("HomeServiceId")
                        .IsUnique()
                        .HasFilter("[HomeServiceId] IS NOT NULL");

                    b.HasIndex("RequestId");

                    b.HasIndex("SuggestionId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ImageCategory = 2,
                            ImagePath = "\\Images\\Category\\1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            ImageCategory = 2,
                            ImagePath = "\\Images\\Category\\2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            ImageCategory = 2,
                            ImagePath = "\\Images\\Category\\3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            ImageCategory = 2,
                            ImagePath = "\\Images\\Category\\4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            ImageCategory = 2,
                            ImagePath = "\\Images\\Category\\5.jpg"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            ImageCategory = 2,
                            ImagePath = "\\Images\\Category\\6.jpg"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            ImageCategory = 2,
                            ImagePath = "\\Images\\Category\\7.jpg"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            ImageCategory = 2,
                            ImagePath = "\\Images\\Category\\8.jpg"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            ImageCategory = 2,
                            ImagePath = "\\Images\\Category\\9.jpg"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            ImageCategory = 2,
                            ImagePath = "\\Images\\Category\\10.jpg"
                        },
                        new
                        {
                            Id = 11,
                            HomeServiceId = 1,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\4-3-3.jpg"
                        },
                        new
                        {
                            Id = 12,
                            HomeServiceId = 2,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\download.jpg"
                        },
                        new
                        {
                            Id = 13,
                            HomeServiceId = 3,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\cleantoilet.jpg"
                        },
                        new
                        {
                            Id = 14,
                            HomeServiceId = 4,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\fixlaundry.jpg"
                        },
                        new
                        {
                            Id = 15,
                            HomeServiceId = 5,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\fixrefrig.jpg"
                        },
                        new
                        {
                            Id = 16,
                            HomeServiceId = 6,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\download (1).jpg"
                        },
                        new
                        {
                            Id = 17,
                            HomeServiceId = 7,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\download (2).jpg"
                        },
                        new
                        {
                            Id = 18,
                            HomeServiceId = 8,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\download (3).jpg"
                        },
                        new
                        {
                            Id = 19,
                            HomeServiceId = 9,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\download (4).jpg"
                        },
                        new
                        {
                            Id = 20,
                            HomeServiceId = 10,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\download (5).jpg"
                        },
                        new
                        {
                            Id = 21,
                            HomeServiceId = 11,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\download (6).jpg"
                        },
                        new
                        {
                            Id = 22,
                            HomeServiceId = 12,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\download (7).jpg"
                        },
                        new
                        {
                            Id = 23,
                            HomeServiceId = 13,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\download (8).jpg"
                        },
                        new
                        {
                            Id = 24,
                            HomeServiceId = 14,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\download (9).jpg"
                        },
                        new
                        {
                            Id = 25,
                            HomeServiceId = 15,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\download (10).jpg"
                        },
                        new
                        {
                            Id = 26,
                            HomeServiceId = 16,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\download (11).jpg"
                        },
                        new
                        {
                            Id = 27,
                            HomeServiceId = 17,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\download (12).jpg"
                        },
                        new
                        {
                            Id = 28,
                            HomeServiceId = 18,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\download (13).jpg"
                        },
                        new
                        {
                            Id = 29,
                            HomeServiceId = 19,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\download (14).jpg"
                        },
                        new
                        {
                            Id = 30,
                            HomeServiceId = 20,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\download (15).jpg"
                        },
                        new
                        {
                            Id = 31,
                            HomeServiceId = 21,
                            ImageCategory = 3,
                            ImagePath = "\\Images\\HomeService\\download (16).jpg"
                        });
                });

            modelBuilder.Entity("Asistant_Domain_Core.RequestAgg.Entity.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentReadyDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HomeServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifyExpertDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("HomeServiceId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Asistant_Domain_Core.SuggestionAgg.Entity.Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<int>("HomeServiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("HomeServiceId");

                    b.HasIndex("RequestId");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("Asistant_Domain_Core.UserAgg.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("ExpertId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("LastName")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5a7f0ac1-5679-456a-a5b8-54bf2b206547",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = 0,
                            Email = "admin@admin.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "09351650512",
                            PasswordHash = "AQAAAAIAAYagAAAAECAO5TIRK7IrDM59Gqpzv2JGmyjlEbDlwlTeJyMxLqktDiqp/WXUHHT8mcBmU3SDRA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fff31c3e-3af8-43f6-9b74-514fab5518f7",
                            TwoFactorEnabled = false,
                            UpdatedUserId = 0,
                            UserName = "09351650512"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Balance = 6000000m,
                            ConcurrencyStamp = "1a8aa04e-a46a-418d-91a3-18b218942a1a",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = 0,
                            CustomerId = 1,
                            Email = "behnaz@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "بهناز",
                            LastName = "بیاتلو",
                            LockoutEnabled = false,
                            NormalizedEmail = "BEHNAZ@GMAIL.COM",
                            NormalizedUserName = "BEHNAZ",
                            PasswordHash = "AQAAAAIAAYagAAAAEA7cqzen1AMbCUiHZWmEo4TPv0zFuI45CUqCfoeX5J3Npsc3P6OuzGW5Ue++CE7Wxg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "25332b44-a82e-43bb-8fe9-3bc1b391170a",
                            TwoFactorEnabled = false,
                            UpdatedUserId = 0,
                            UserName = "behnaz"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            Balance = 4000000m,
                            ConcurrencyStamp = "99ce8591-047b-4c15-9aba-8d22b690919d",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = 0,
                            CustomerId = 2,
                            Email = "hasan@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "حسن",
                            LastName = "اسدی",
                            LockoutEnabled = false,
                            NormalizedEmail = "HASAN@GMAIL.COM",
                            NormalizedUserName = "HASAN",
                            PasswordHash = "AQAAAAIAAYagAAAAEO6mIyIgw44cx0hE61m+o29ea6yynEw7VwER4oF/WpYTLR6lXWhkgvs3+OxgHo7HRw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "62a0d7df-957f-45c2-82e3-1c3968006b1e",
                            TwoFactorEnabled = false,
                            UpdatedUserId = 0,
                            UserName = "hasan"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5a1f7701-3d64-4123-a510-1d6e59ca673a",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = 0,
                            Email = "mohammad@gmail.com",
                            EmailConfirmed = false,
                            ExpertId = 1,
                            FirstName = "محمد",
                            LastName = "اکبری",
                            LockoutEnabled = false,
                            NormalizedEmail = "MOHAMMAD@GMAIL.COM",
                            NormalizedUserName = "MOHAMMAD",
                            PasswordHash = "AQAAAAIAAYagAAAAEHuRGfH/L3bO76WxrRnNxHTnwpWhDTbijuSVRWstapHqcglWcUqWaTZHuzdG76S/aA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "91b77534-7def-4eca-b5f2-512bc1199f02",
                            TwoFactorEnabled = false,
                            UpdatedUserId = 0,
                            UserName = "mohammad"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "09c5d83f-c2cc-40e3-9cdf-bcfc99d4e9e5",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = 0,
                            Email = "majid@gmail.com",
                            EmailConfirmed = false,
                            ExpertId = 2,
                            FirstName = "مجید",
                            LastName = "بیگی",
                            LockoutEnabled = false,
                            NormalizedEmail = "MAJID@GMAIL.COM",
                            NormalizedUserName = "MAJID",
                            PasswordHash = "AQAAAAIAAYagAAAAEH8bLXtLX15vX3bxErCPSDpK+xloz2sYjvsMitTgvh8YslfyxwQoKbTPJ5TFzx+8Xg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8f8af664-c1af-466d-8baa-2a792260f549",
                            TwoFactorEnabled = false,
                            UpdatedUserId = 0,
                            UserName = "majid"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2e57ff53-1405-4744-a009-67ed6c49fd73",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = 0,
                            Email = "meysam@gmail.com",
                            EmailConfirmed = false,
                            ExpertId = 3,
                            FirstName = "میثم",
                            LastName = "محسنی",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEYSAM@GMAIL.COM",
                            NormalizedUserName = "MEYSAM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPtv/xiJG61ZTA48+YDCLxJ8o/MM0d6KK6X1nTwuGuac1RJhWCDSTAWOjPuY1Sne2Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3b0fd3a8-e465-4d93-a1f1-a268fadd7000",
                            TwoFactorEnabled = false,
                            UpdatedUserId = 0,
                            UserName = "meysam"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6bcb1d81-02eb-43ad-a33e-1887489b643a",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = 0,
                            Email = "saman@gmail.com",
                            EmailConfirmed = false,
                            ExpertId = 4,
                            FirstName = "سامان",
                            LastName = "جلیلی",
                            LockoutEnabled = false,
                            NormalizedEmail = "SAMAN@GMAIL.COM",
                            NormalizedUserName = "SAMAN",
                            PasswordHash = "AQAAAAIAAYagAAAAEEDj679FkVnrdjn7WS06ccs0L05+160n7iU7dq2yP10HYI90n72RkhvjedBcdpkTjA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8457ba2d-aa69-4d33-94b8-d9e579079bec",
                            TwoFactorEnabled = false,
                            UpdatedUserId = 0,
                            UserName = "saman"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "de13c1ea-a487-40fa-ba7f-fb8c08dd8886",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = 0,
                            Email = "sara@gmail.com",
                            EmailConfirmed = false,
                            ExpertId = 5,
                            FirstName = "سارا",
                            LastName = "دلشاد",
                            LockoutEnabled = false,
                            NormalizedEmail = "SARA@GMAIL.COM",
                            NormalizedUserName = "SARA",
                            PasswordHash = "AQAAAAIAAYagAAAAEBrHUkrJSn9f5tX+YvPkvx0wtgre2TGyLb28KcfUeirLeAzUXAzeQl0IMVr5vrfrZA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cb376523-5b0d-47a0-b205-62fe110a8e3c",
                            TwoFactorEnabled = false,
                            UpdatedUserId = 0,
                            UserName = "sara"
                        });
                });

            modelBuilder.Entity("Asistant_Domain_Core.UserAgg.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "تهران"
                        },
                        new
                        {
                            Id = 2,
                            Name = "مشهد"
                        },
                        new
                        {
                            Id = 3,
                            Name = "اصفهان"
                        },
                        new
                        {
                            Id = 4,
                            Name = "شیراز"
                        },
                        new
                        {
                            Id = 5,
                            Name = "تبریز"
                        },
                        new
                        {
                            Id = 6,
                            Name = "کرج"
                        },
                        new
                        {
                            Id = 7,
                            Name = "قم"
                        },
                        new
                        {
                            Id = 8,
                            Name = "اهواز"
                        },
                        new
                        {
                            Id = 9,
                            Name = "کرمانشاه"
                        },
                        new
                        {
                            Id = 10,
                            Name = "رشت"
                        },
                        new
                        {
                            Id = 11,
                            Name = "یزد"
                        },
                        new
                        {
                            Id = 12,
                            Name = "کرمان"
                        },
                        new
                        {
                            Id = 13,
                            Name = "ارومیه"
                        },
                        new
                        {
                            Id = 14,
                            Name = "زاهدان"
                        },
                        new
                        {
                            Id = 15,
                            Name = "ساری"
                        });
                });

            modelBuilder.Entity("Asistant_Domain_Core.UserAgg.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "تهران خیابان ایت الله کاشانی کوچه بهنام پلاک 4 واحد1",
                            CityId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Address = "شیراز بلوار سعدی کوچه پرستو پلاک 12 واحد 2 ",
                            CityId = 4,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Asistant_Domain_Core.UserAgg.Entities.Expert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Experts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            CityId = 4,
                            UserId = 5
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            UserId = 6
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 5,
                            CityId = 1,
                            UserId = 8
                        });
                });

            modelBuilder.Entity("ExpertHomeService", b =>
                {
                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<int>("HomeServiceId")
                        .HasColumnType("int");

                    b.HasKey("ExpertId", "HomeServiceId");

                    b.HasIndex("HomeServiceId");

                    b.ToTable("ExpertHomeServices", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Expert",
                            NormalizedName = "EXPERT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Asistant_Domain_Core.CommentAgg.Entity.Comment", b =>
                {
                    b.HasOne("Asistant_Domain_Core.UserAgg.Entities.Customer", "Customer")
                        .WithMany("Comments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Asistant_Domain_Core.UserAgg.Entities.Expert", "Expert")
                        .WithMany("Comments")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Asistant_Domain_Core.HomeServiceAgg.Entities.HomeService", "HomeService")
                        .WithMany("Comments")
                        .HasForeignKey("HomeServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Expert");

                    b.Navigation("HomeService");
                });

            modelBuilder.Entity("Asistant_Domain_Core.HomeServiceAgg.Entities.HomeService", b =>
                {
                    b.HasOne("Asistant_Domain_Core.HomeServiceAgg.Entities.Category", "Category")
                        .WithMany("HomeServices")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Asistant_Domain_Core.ImageAgg.Entity.Image", b =>
                {
                    b.HasOne("Asistant_Domain_Core.HomeServiceAgg.Entities.Category", "Category")
                        .WithOne("Image")
                        .HasForeignKey("Asistant_Domain_Core.ImageAgg.Entity.Image", "CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Asistant_Domain_Core.UserAgg.Entities.Customer", "Customer")
                        .WithOne("Image")
                        .HasForeignKey("Asistant_Domain_Core.ImageAgg.Entity.Image", "CustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Asistant_Domain_Core.UserAgg.Entities.Expert", "Expert")
                        .WithOne("Image")
                        .HasForeignKey("Asistant_Domain_Core.ImageAgg.Entity.Image", "ExpertId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Asistant_Domain_Core.HomeServiceAgg.Entities.HomeService", "HomeService")
                        .WithOne("Image")
                        .HasForeignKey("Asistant_Domain_Core.ImageAgg.Entity.Image", "HomeServiceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Asistant_Domain_Core.RequestAgg.Entity.Request", "Request")
                        .WithMany("Images")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Asistant_Domain_Core.SuggestionAgg.Entity.Suggestion", "Suggestion")
                        .WithMany("Images")
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");

                    b.Navigation("Customer");

                    b.Navigation("Expert");

                    b.Navigation("HomeService");

                    b.Navigation("Request");

                    b.Navigation("Suggestion");
                });

            modelBuilder.Entity("Asistant_Domain_Core.RequestAgg.Entity.Request", b =>
                {
                    b.HasOne("Asistant_Domain_Core.UserAgg.Entities.Customer", "Customer")
                        .WithMany("Requests")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Asistant_Domain_Core.HomeServiceAgg.Entities.HomeService", "HomeService")
                        .WithMany("Requests")
                        .HasForeignKey("HomeServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("HomeService");
                });

            modelBuilder.Entity("Asistant_Domain_Core.SuggestionAgg.Entity.Suggestion", b =>
                {
                    b.HasOne("Asistant_Domain_Core.UserAgg.Entities.Expert", "Expert")
                        .WithMany("Suggestions")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Asistant_Domain_Core.HomeServiceAgg.Entities.HomeService", "HomeService")
                        .WithMany("Suggestions")
                        .HasForeignKey("HomeServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Asistant_Domain_Core.RequestAgg.Entity.Request", "Request")
                        .WithMany("Suggestions")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("HomeService");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Asistant_Domain_Core.UserAgg.Entities.Customer", b =>
                {
                    b.HasOne("Asistant_Domain_Core.UserAgg.Entities.City", "City")
                        .WithMany("Customers")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Asistant_Domain_Core.UserAgg.Entities.AppUser", "User")
                        .WithOne("Customer")
                        .HasForeignKey("Asistant_Domain_Core.UserAgg.Entities.Customer", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Asistant_Domain_Core.UserAgg.Entities.Expert", b =>
                {
                    b.HasOne("Asistant_Domain_Core.UserAgg.Entities.City", "City")
                        .WithMany("Experts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Asistant_Domain_Core.UserAgg.Entities.AppUser", "User")
                        .WithOne("Expert")
                        .HasForeignKey("Asistant_Domain_Core.UserAgg.Entities.Expert", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpertHomeService", b =>
                {
                    b.HasOne("Asistant_Domain_Core.UserAgg.Entities.Expert", null)
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Asistant_Domain_Core.HomeServiceAgg.Entities.HomeService", null)
                        .WithMany()
                        .HasForeignKey("HomeServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Asistant_Domain_Core.UserAgg.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Asistant_Domain_Core.UserAgg.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Asistant_Domain_Core.UserAgg.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Asistant_Domain_Core.UserAgg.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Asistant_Domain_Core.HomeServiceAgg.Entities.Category", b =>
                {
                    b.Navigation("HomeServices");

                    b.Navigation("Image")
                        .IsRequired();
                });

            modelBuilder.Entity("Asistant_Domain_Core.HomeServiceAgg.Entities.HomeService", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Image")
                        .IsRequired();

                    b.Navigation("Requests");

                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("Asistant_Domain_Core.RequestAgg.Entity.Request", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("Asistant_Domain_Core.SuggestionAgg.Entity.Suggestion", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Asistant_Domain_Core.UserAgg.Entities.AppUser", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("Asistant_Domain_Core.UserAgg.Entities.City", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Experts");
                });

            modelBuilder.Entity("Asistant_Domain_Core.UserAgg.Entities.Customer", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Image");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Asistant_Domain_Core.UserAgg.Entities.Expert", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Image");

                    b.Navigation("Suggestions");
                });
#pragma warning restore 612, 618
        }
    }
}
